### ISSUE TITLE
So great ! a simple question - Right on folder upload

### ISSUE THREAD

**Issue by alan345** [predatorkill/ng2-forms-demo#2]
Thanks you very much for this stack ! It is very useful!
Just a quick question, I have created man manually folders uploads/forms and uploads/profile because they were not created automativcally.

When I upload an image, I got this error:

{ Error: ENOENT: no such file or directory, mkdir 'server/uploads/profiles/584f2caf704c834fda6c2a29'
    at Error (native)
    at Object.fs.mkdirSync (fs.js:922:18)
    at DiskStorage.destination [as getDestination] (/Users/alan/app/ng2-form-demo/server/routes/user.js:131:10)
    at DiskStorage._handleFile (/Users/alan/app/ng2-form-demo/node_modules/multer/storage/disk.js:31:8)
    at /Users/alan/app/ng2-form-demo/node_modules/multer/lib/make-middleware.js:142:17
    at fileFilter (/Users/alan/app/ng2-form-demo/server/routes/user.js:158:14)
    at wrappedFileFilter (/Users/alan/app/ng2-form-demo/node_modules/multer/index.js:43:7)
    at Busboy.<anonymous> (/Users/alan/app/ng2-form-demo/node_modules/multer/lib/make-middleware.js:112:7)
    at emitMany (events.js:127:13)
    at Busboy.emit (events.js:201:7)
    at Busboy.emit (/Users/alan/app/ng2-form-demo/node_modules/busboy/lib/main.js:31:35)
    at PartStream.<anonymous> (/Users/alan/app/ng2-form-demo/node_modules/busboy/lib/types/multipart.js:213:13)
    at emitOne (events.js:96:13)
    at PartStream.emit (events.js:188:7)
    at HeaderParser.<anonymous> (/Users/alan/app/ng2-form-demo/node_modules/dicer/lib/Dicer.js:51:16)
    at emitOne (events.js:96:13)
  errno: -2,
  code: 'ENOENT',
  syscall: 'mkdir',
  path: 'server/uploads/profiles/584f2caf704c834fda6c2a29' }

I guess it is a Right on a folder issue ? 

Thanks for your help

**Comment by alan345** [comment]
resolved. I have installed GraphicsMagick.
But i have created manually folders uploads/forms and uploads/profile

**Comment by efstathiosntonas** [comment]
Hi alan345, thanks for you kind words.

Yes, you should create the folders, I will update the seed.js to create them automatically. Right now I don't push the uploads folder to github, my bad!

**Comment by alan345** [comment]
Great ! One more thing, if you login to a user, logout and then login to another login cookies are not refreshed. Page must be refreshed to get new data. 

I am going to implement few things like pagination, automplete, user roles and permissions.. based on your code. Let me know are interested of this code. 

Thanks again and again, very good job

**Comment by efstathiosntonas** [comment]
I m into fixing these bugs but last week had no time! Make a pull request or a fork and do whatever you want!

**Comment by alan345** [comment]
I have added a few things like pagination. I have updated your latest version.
https://github.com/alan345/ng2-form-demo
Let me know if you want me to do a pull request.
(we still have the cookie issue when we change session to another login)
Thanks again

**Comment by alan345** [comment]
Hello ! Hope you are doing well. What is the best direction to solve the login /cookie issue . 
(if you login to a user, logout and then login to another login cookies are not refreshed. Page must be refreshed to get new data into the cookies)

Force to refresh page when jwt is not correct. ? Thanks for your help

**Comment by efstathiosntonas** [comment]
Hi,

Best way is to use the AuthHttp from angular2-jwt package, their readme has all the info you need in order to make it work. If you need any help leave a comment.

**Comment by efstathiosntonas** [comment]
Project updated to use Angular 4, introduced AuthHttp to fix login issues.

I've also changed upload logic, you'll need to update or clone the repo.
